SELECT
  a.id                  AS pid,
  0                     AS padre,
  ''                    AS shopify,
  b.bodega_desc         AS sucursal,
  ''                    AS rso,
  ''                    AS rut,
  a.desde               AS creado,
  a.desde               AS dt_picking,
  a.desde               AS facturar,
  a.desde               AS facturado,
  a.desde               AS confirmado,
  a.desde               AS entregado,
  a.desde               AS vencimiento,
  ''                    AS guia,
  ''                    AS factura,
  0                     AS neto,
  0                     AS iva,
  0                     AS total,
  0                     AS deuda,
  ''                    AS sku,
  a.descripcion         AS nombre,
  ''                    AS descripcion,
  1                     AS qty,
  1                     AS picking,
  ROUND(a.diferencia)   AS pu,
  ''                    AS tramo,
  0                     AS pmp,
  0                     AS totaliza_pmp,
  0                     AS totaliza_vta,
  ROUND(a.diferencia)   AS margen,
  u.tcomision,
  ''                    AS observacion,
  CONCAT(u.user_name,' ',u.user_apellido) AS vendedor,
  a.rut                AS rut_vendedor,
  a.remuneracion       AS remunera,
  ''                   AS comuna,
  ''                   AS direccion,
  ''                   AS area,
  ''                   AS procedencia,
  ''                   AS marca,
  ''                   AS familia,
  ''                   AS tipo
FROM mstr_anexo a
JOIN tab_bodegas b ON a.sucursal_id = b.bodega_id
JOIN tab_users u   ON a.rut = u.user_rut
WHERE a.desde >= '{{ start_date }}' AND a.desde < '{{ end_date }}';
